source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'rails-api'


gem 'sqlite3'

gem 'bcrypt'
gem 'active_type'

gem 'shoulda-context', group: :test

group :development do
  gem 'spring'
  gem 'annotate'
end
